import tensorflow as tf


hparams = tf.contrib.training.HParams(
    source='./data/sample.en',
    target='./data/sample.kr',
    bpe_num_symbols=128,
    sos='<s>',
    eos='</s>',
    pad='<pad>',
    unk='<unk>',
    batch_size=16,
    src_max_len=0,
    tgt_max_len=0,
    infer_src_max_len=200,
    infer_tgt_max_len=200,
    num_units=64,
    num_layers_encoder=2,
    num_layers_decoder=2,
    optimizer='adam',
    learning_rate=0.0001,
    final_learning_rate=0.00002,
    warmup_steps=4000,
    bucket=0,
    attention_mechanism='scaled_luong',
    beam_width=1,
    encoder_type='bi',
    unit_type='gru',
    dropout=0.1,
    num_residual_layers=0,
)
